### ISSUE TITLE
Mini issue tracker

### ISSUE THREAD

**Issue by maehr** [digihistch24/abstract-template#2]
- [x] Remove Zenodo badge
- [x] Remove Security section
- [x] Enhance docs for non technical people
- [x] Add dummy image to template
- [x] Add dummy r or python code section to template
- [ ] fix licensing badge
